### ISSUE TITLE
Editable Value for Custom Background CSS

### ISSUE THREAD

**Issue by TaQuangKhoi** [TaQuangKhoi/RemNote-CSS-Library-by-Keios#1]
```css
:root {
--my-background-color: #fff;
}
```
