### ISSUE TITLE
Wrong Guide: Custom Background not work with

### ISSUE THREAD

**Issue by TaQuangKhoi** [TaQuangKhoi/RemNote-CSS-Library-by-Keios#2]
this code
```css
:root {
    --my-background-color: #f7f5f3; /* Use your favorite color */
}
@import url("https://taquangkhoi.github.io/RemNote-CSS-Library-by-Keios/Custom-Background.css");
```
